# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'svd_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 481))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.login_tab = QtWidgets.QWidget()
        self.login_tab.setObjectName("login_tab")
        self.main_title_label = QtWidgets.QLabel(self.login_tab)
        self.main_title_label.setGeometry(QtCore.QRect(270, 20, 201, 41))
        self.main_title_label.setObjectName("main_title_label")
        self.frame_4 = QtWidgets.QFrame(self.login_tab)
        self.frame_4.setGeometry(QtCore.QRect(10, 80, 301, 261))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 271, 251))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.user_name_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.user_name_label.setObjectName("user_name_label")
        self.verticalLayout_4.addWidget(self.user_name_label)
        self.user_name_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.user_name_line_edit.setObjectName("user_name_line_edit")
        self.verticalLayout_4.addWidget(self.user_name_line_edit)
        self.password_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.password_label.setObjectName("password_label")
        self.verticalLayout_4.addWidget(self.password_label)
        self.password_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.password_line_edit.setObjectName("password_line_edit")
        self.verticalLayout_4.addWidget(self.password_line_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.frame_5 = QtWidgets.QFrame(self.login_tab)
        self.frame_5.setGeometry(QtCore.QRect(350, 80, 301, 261))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_5)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 271, 251))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.video_confirmation_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.video_confirmation_label.setObjectName("video_confirmation_label")
        self.verticalLayout_5.addWidget(self.video_confirmation_label)
        self.random_sequence_lcd_number = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.random_sequence_lcd_number.setDigitCount(8)
        self.random_sequence_lcd_number.setProperty("value", 12345678.0)
        self.random_sequence_lcd_number.setObjectName("random_sequence_lcd_number")
        self.verticalLayout_5.addWidget(self.random_sequence_lcd_number)
        self.record_video_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.record_video_button.setObjectName("record_video_button")
        self.verticalLayout_5.addWidget(self.record_video_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.browse_video_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.browse_video_button.setObjectName("browse_video_button")
        self.verticalLayout_5.addWidget(self.browse_video_button)
        self.pushButton = QtWidgets.QPushButton(self.login_tab)
        self.pushButton.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.login_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 311, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.histogram__comparison_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.histogram__comparison_label.setObjectName("histogram__comparison_label")
        self.verticalLayout_2.addWidget(self.histogram__comparison_label)
        self.custom_chi_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.custom_chi_checkbox.setObjectName("custom_chi_checkbox")
        self.verticalLayout_2.addWidget(self.custom_chi_checkbox)
        self.opencv_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.opencv_checkbox.setObjectName("opencv_checkbox")
        self.verticalLayout_2.addWidget(self.opencv_checkbox)
        self.numpy_textbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.numpy_textbox.setObjectName("numpy_textbox")
        self.verticalLayout_2.addWidget(self.numpy_textbox)
        self.histogram_comparison_set_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.histogram_comparison_set_button.setObjectName("histogram_comparison_set_button")
        self.verticalLayout_2.addWidget(self.histogram_comparison_set_button)
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 240, 311, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 291, 204))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.histogram_similarity_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.histogram_similarity_label.setObjectName("histogram_similarity_label")
        self.verticalLayout.addWidget(self.histogram_similarity_label)
        self.hs_custom_chi_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hs_custom_chi_label.setObjectName("hs_custom_chi_label")
        self.verticalLayout.addWidget(self.hs_custom_chi_label)
        self.custom_chi_spinbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.custom_chi_spinbox.setDecimals(3)
        self.custom_chi_spinbox.setMaximum(5.0)
        self.custom_chi_spinbox.setSingleStep(0.001)
        self.custom_chi_spinbox.setObjectName("custom_chi_spinbox")
        self.verticalLayout.addWidget(self.custom_chi_spinbox)
        self.hs_opencv_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hs_opencv_label.setObjectName("hs_opencv_label")
        self.verticalLayout.addWidget(self.hs_opencv_label)
        self.opencv_spinbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.opencv_spinbox.setDecimals(3)
        self.opencv_spinbox.setMaximum(5.0)
        self.opencv_spinbox.setSingleStep(0.001)
        self.opencv_spinbox.setObjectName("opencv_spinbox")
        self.verticalLayout.addWidget(self.opencv_spinbox)
        self.hs_numpy_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hs_numpy_label.setObjectName("hs_numpy_label")
        self.verticalLayout.addWidget(self.hs_numpy_label)
        self.numpy_spinbox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.numpy_spinbox.setDecimals(3)
        self.numpy_spinbox.setMaximum(5.0)
        self.numpy_spinbox.setSingleStep(0.001)
        self.numpy_spinbox.setObjectName("numpy_spinbox")
        self.verticalLayout.addWidget(self.numpy_spinbox)
        self.similarity_set_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.similarity_set_button.setObjectName("similarity_set_button")
        self.verticalLayout.addWidget(self.similarity_set_button)
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(350, 10, 311, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 291, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.checkBox_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_7 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_3.addWidget(self.checkBox_7)
        self.facial_recognition_set_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.facial_recognition_set_button.setObjectName("facial_recognition_set_button")
        self.verticalLayout_3.addWidget(self.facial_recognition_set_button)
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(350, 240, 311, 211))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(1)
        self.frame_6.setMidLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.frame_6)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 291, 171))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scene_detect_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.scene_detect_label.setObjectName("scene_detect_label")
        self.verticalLayout_6.addWidget(self.scene_detect_label)
        self.scene_detect_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.scene_detect_checkbox.setEnabled(True)
        self.scene_detect_checkbox.setObjectName("scene_detect_checkbox")
        self.verticalLayout_6.addWidget(self.scene_detect_checkbox)
        self.scene_detect_threshold_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.scene_detect_threshold_label.setObjectName("scene_detect_threshold_label")
        self.verticalLayout_6.addWidget(self.scene_detect_threshold_label)
        self.scene_detect_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.scene_detect_spinbox.setObjectName("scene_detect_spinbox")
        self.verticalLayout_6.addWidget(self.scene_detect_spinbox)
        self.facial_recognition_set_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.facial_recognition_set_button_2.setObjectName("facial_recognition_set_button_2")
        self.verticalLayout_6.addWidget(self.facial_recognition_set_button_2)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spliced Video Detector"))
        self.main_title_label.setText(_translate("MainWindow", "Spliced Video Detector"))
        self.user_name_label.setText(_translate("MainWindow", "User Name"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.video_confirmation_label.setText(_translate("MainWindow", "Video Confirmation"))
        self.record_video_button.setText(_translate("MainWindow", "Record video"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop Recording"))
        self.browse_video_button.setText(_translate("MainWindow", "Browse for video"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login_tab), _translate("MainWindow", "Login"))
        self.histogram__comparison_label.setText(_translate("MainWindow", "Histogram Comparison"))
        self.custom_chi_checkbox.setText(_translate("MainWindow", "Custom Chi"))
        self.opencv_checkbox.setText(_translate("MainWindow", "OpenCV"))
        self.numpy_textbox.setText(_translate("MainWindow", "NumPy"))
        self.histogram_comparison_set_button.setText(_translate("MainWindow", "Set"))
        self.histogram_similarity_label.setText(_translate("MainWindow", "Histogram similarity threshold"))
        self.hs_custom_chi_label.setText(_translate("MainWindow", "Custom Chi"))
        self.hs_opencv_label.setText(_translate("MainWindow", "OpenCV"))
        self.hs_numpy_label.setText(_translate("MainWindow", "NumPy"))
        self.similarity_set_button.setText(_translate("MainWindow", "Set"))
        self.label_6.setText(_translate("MainWindow", "Facial Recognition"))
        self.checkBox_5.setText(_translate("MainWindow", "Check for face in video"))
        self.checkBox_7.setText(_translate("MainWindow", "Crop Face"))
        self.facial_recognition_set_button.setText(_translate("MainWindow", "Set"))
        self.scene_detect_label.setText(_translate("MainWindow", "SceneDetect"))
        self.scene_detect_checkbox.setText(_translate("MainWindow", "Use SceneDetect"))
        self.scene_detect_threshold_label.setText(_translate("MainWindow", "SceneDetect Threshold"))
        self.facial_recognition_set_button_2.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

